### ISSUE TITLE
Merging in the new `cs-poppy` implementation

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Succinct-Vector-Library#5]
@newhoggy : So I'm coming close to merging in my alternative implementation.  My original intention was to completely replace old implementation but given the work that you've begun putting into it I wanted to know if you wanted to keep both implementations side by side or if you're fine switching to the new implementation.

To provide some context, the main reasons that I'm switching to the new implementation are:
- Significantly smaller footprint
  
  The final index is ~3% of the size of the input data, as opposed to 87.5% of the size for the current implementation
- Faster to index
  
  The new index is simpler and significantly easier to build so I can index hundreds of megabytes of data per second, which is much faster than I can do with the old implementation
- Easier to prove correct
  
  If you've been studying the source code you know that I have Liquid Haskell annotations everywhere but I ran into a wall trying to prove the existing implementation correct (and clearly it's not correct as your newly added test case indicates).  However, I'm pretty close to proving the new implementation correct, which matters a lot to me because I want this algorithmic building block to be rock solid.

However, there's one major disadvantage which is that query time is slower.  The newer index is roughly 5x slower to query, but still pretty fast in absolute terms (for example, ~60 ns for rank query with new index as opposed to ~12 ns query for current index).  It's also O(log N) instead of O(1) time complexity.

I don't really plan on supporting the old implementation any longer but if you want to keep improving on it I will keep them side-by-side.  Otherwise, if you prefer to just use the new implementation then I will replace the old one.

**Comment by newhoggy** [comment]
Thanks for you message.

If possible I would like to keep the `rank9` implementation because I'm planning some query heavy applications.

There is still the possibility that `rank9` doesn't give the kind of query performance characteristics under my use case and that `cs-poppy` works better, (maybe for example due to I/O saturation).  In that case, I'll let you know.

BTW, Have you considered having multiple implementations with quick checks to confirm all the implementations give the same results?

PS. the fast indexing of `cs-poppy` sounds really handy.  What are you intending to use it for?

**Comment by Gabriel439** [comment]
I have three applications in mind for succinct vectors + succinct trees:

* Big data processing for unstructured data
* High-performance source code refactoring tools (for large repositories)
* Possibly network packet analysis

In the first case I need fast indexing speed because the data is so large.  In the latter two cases I need fast indexing speed because the number of queries per index will be relatively low, but still high enough that it's worth indexing.

**Comment by newhoggy** [comment]
It may be some time before I get around to fixing the indexing issues because I want to prove out some rank-select based data structures and demonstrate something useful.

If it helps, so you can get green builds again and since all the code is in the history anyway, I think it is reasonable to replace to code at this stage.

I can always revisit the `rank9` implementation later when it is more convenient and re-contribute it.

**Comment by newhoggy** [comment]
Also, I couldn't help noticing, the benchmarks for `cs-poppy` vs `rank9` in the paper "Space-Efficient, High-Performance Rank & Select Structures on Uncompressed Bit Sequences" don't look too shabby.

Maybe this `cs-poppy` implementation you are merging could be optimised further and I won't need `rank9`?

**Comment by Gabriel439** [comment]
Yeah, the paper shows that `cs-poppy` should be competitive with `rank9` and I'm trying to see if I can optimize it further to match `rank9`.

**Comment by newhoggy** [comment]
:+1:

**Comment by newhoggy** [comment]
How are things going?

I've been wondering if the performance concerns you note might actually be down the performance of the `popCount` function.

The paper dedicates enough discussion to the `x86` `popCount` instruction to suggest to me that it was critical to the authors getting the performance characteristics they sought.

If that's the case, maybe your implementation is already good and we just need a good performance `popCount` function from GHC?

**Comment by newhoggy** [comment]
Hi Gabriel,

I benchmarked your broadword `popCount` implementation against the GHC version to investigate why your version was faster.

This was your version:

```
popCount1 x0 = ((x3 * 0x0101010101010101) .>. 56)
    where
      x1 = x0 - ((x0 .&. 0xaaaaaaaaaaaaaaaa) .>. 1)
      x2 = (x1 .&. 0x3333333333333333) + ((x1 .>. 2) .&. 0x3333333333333333)
      x3 = (x2 + (x2 .>. 4)) .&. 0x0f0f0f0f0f0f0f0f
```

This is the benchmark code I used:

```
main = defaultMain
  [ env setupEnv (\bv -> bgroup "Rank"
    [ bench "PopCnt1 Broadword - Once" (nf   (map (\n -> getCount (PC1BW.popCount1  (DVS.take n bv)))) [0, 1000..100000])
    , bench "PopCnt1 GHC       - Once" (nf   (map (\n -> getCount (PC1GHC.popCount1 (DVS.take n bv)))) [0, 1000..100000])
    ] )
  ]
```

I got the following results:

```
benchmarking Rank/PopCnt1 Broadword - Once
time                 18.49 ms   (17.89 ms .. 19.08 ms)
                     0.994 R²   (0.989 R² .. 0.998 R²)
mean                 19.62 ms   (19.22 ms .. 20.04 ms)
std dev              1.026 ms   (846.2 μs .. 1.315 ms)
variance introduced by outliers: 21% (moderately inflated)

benchmarking Rank/PopCnt1 GHC       - Once
time                 36.80 ms   (36.25 ms .. 37.57 ms)
                     0.998 R²   (0.996 R² .. 1.000 R²)
mean                 37.14 ms   (36.72 ms .. 37.97 ms)
std dev              1.100 ms   (650.6 μs .. 1.680 ms)
```

Which confirm the broadword implementation was faster.

Then I went to the GHC source code to see what it was actually doing and found this snippet which suggests I need to enable `SSE4.2` to make the built-in `popCount` fast:

```

genCCall dflags is32Bit (PrimTarget (MO_PopCnt width)) dest_regs@[dst]
         args@[src] = do
    sse4_2 <- sse4_2Enabled
    let platform = targetPlatform dflags
    if sse4_2
        then do code_src <- getAnyReg src
                src_r <- getNewRegNat format
                let dst_r = getRegisterReg platform False (CmmLocal dst)
                return $ code_src src_r `appOL`
                    (if width == W8 then
                         -- The POPCNT instruction doesn't take a r/m8
                         unitOL (MOVZxL II8 (OpReg src_r) (OpReg src_r)) `appOL`
                         unitOL (POPCNT II16 (OpReg src_r) dst_r)
                     else
                         unitOL (POPCNT format (OpReg src_r) dst_r)) `appOL`
                    (if width == W8 || width == W16 then
                         -- We used a 16-bit destination register above,
                         -- so zero-extend
                         unitOL (MOVZxL II16 (OpReg dst_r) (OpReg dst_r))
                     else nilOL)
        else do
            targetExpr <- cmmMakeDynamicReference dflags
                          CallReference lbl
            let target = ForeignTarget targetExpr (ForeignConvention CCallConv
                                                           [NoHint] [NoHint]
                                                           CmmMayReturn)
            genCCall dflags is32Bit target dest_regs args
```

So I added the relevant flag to bench:

```
    GHC-Options: -O2 -Wall -msse4.2
```

And now the GHC built-in `popCount` is faster than the broadword:

```
time                 18.45 ms   (18.25 ms .. 18.67 ms)
                     0.999 R²   (0.997 R² .. 0.999 R²)
mean                 18.19 ms   (17.99 ms .. 18.38 ms)
std dev              508.6 μs   (398.6 μs .. 623.8 μs)

benchmarking Rank/PopCnt1 GHC       - Once
time                 11.82 ms   (11.65 ms .. 11.97 ms)
                     0.999 R²   (0.998 R² .. 0.999 R²)
mean                 11.85 ms   (11.74 ms .. 11.96 ms)
std dev              283.5 μs   (229.6 μs .. 362.8 μs)
```

Hope that helps.

**Comment by Gabriel439** [comment]
Sorry for the delayed reply.  I want to clarify that the performance gap is not the reason I haven't done the switch yet.  I'm actually really happy with the new implementation and I've already decided to make the switch.  I just wanted to polish it (i.e. tidy up the documentation and API) before merging it into `master` and I just need more time to do that and I'm slowly catching up on other responsibilities first before returning to this project.

However, it's still really exciting to see that there are huge performance gains waiting to be had just by switching to a more efficient `popCount`! :)

**Comment by newhoggy** [comment]
Yay!

**Comment by vaibhavsagar** [comment]
It looks like the new `cs-poppy` implementation has been merged. May I close this?

**Comment by Gabriella439** [comment]
@vaibhavsagar: Yeah, this is complete
