### ISSUE TITLE
CI, Green builds and PRs

### ISSUE THREAD

**Issue by newhoggy** [Gabriel439/Haskell-Succinct-Vector-Library#6]
I was wondering if you were interesting in setting up CircleCI for your succinct vector library.

It will tell you:

* whether your build is Green (compiles and passes tests)
* if someone's pull request is Green

Here is an example:

https://circleci.com/gh/haskell-works/hw-succinct

It doesn't require much, just a `circle.yml` file, and you need login to https://circleci.com and click a few things to enable the build.

**Comment by Gabriel439** [comment]
I've been using Travis for most of my other projects, but just hadn't enabled it for this one yet.  Would Travis be alright with you or are there any specific features that you prefer about CircleCI.

**Comment by newhoggy** [comment]
I've used both.  Main advantage I can see with CircleCI, is I can ssh into the build to debug CI specific problems, eg. deployment or test only fails on CI, or figuring out why builds on CI are slow.

**Comment by Gabriel439** [comment]
I decided to use Travis for now and added support in this commit: https://github.com/Gabriel439/Haskell-Succinct-Vector-Library/commit/544deadf107ff80bdbcc2e78f79d1d8a17bc1bd6

**Comment by newhoggy** [comment]
:+1:
